### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by beardroid2005** [infiniteautomation/modbus4j#1]
Hi

I have downloaded the library.

I tried to compile the project but the build failed

An error has occurred while processing the Maven artifact tasks.
[mvn:dependencies]  Diagnosis:
[mvn:dependencies] 
[mvn:dependencies] Unable to resolve artifact: Missing:
[mvn:dependencies] ----------
[mvn:dependencies] 1) com.serotonin:serotonin-utils:jar:2.1.6
[mvn:dependencies] 
[mvn:dependencies]   Try downloading the file manually from the project website.
[mvn:dependencies] 
[mvn:dependencies]   Then, install it using the command: 
[mvn:dependencies]       mvn install:install-file -DgroupId=com.serotonin -DartifactId=serotonin-utils -Dversion=2.1.6 -Dpackaging=jar -Dfile=/path/to/file
[mvn:dependencies] 
[mvn:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[mvn:dependencies]       mvn deploy:deploy-file -DgroupId=com.serotonin -DartifactId=serotonin-utils -Dversion=2.1.6 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[mvn:dependencies] 
[mvn:dependencies]   Path to dependency: 
[mvn:dependencies]   	1) com.infiniteautomation:modbus4j:jar:2.0.6
[mvn:dependencies]   	2) com.serotonin:serotonin-utils:jar:2.1.6

Into the modbus4j-maven-local, the last version available is the 2.1.4
I changed the version in pom.xml, but some classes are missing
- EpollStreamTransportCharSpaced
- StreamTransportCharSpaced

Could you add the latest version to modbus4j-maven-local?

Regards

Daniele

**Comment by beardroid2005** [comment]
Thanks.

daniele

**Comment by jederfreitas** [comment]
Obrigado

**Comment by murilosamuel** [comment]
@jederfreitas, english please.
