### ISSUE TITLE
Repo ias-release 503 ERROR

### ISSUE THREAD

**Issue by VergLsm** [infiniteautomation/modbus4j#11]
https://maven.mangoautomation.net/repository/ias-release
This repo 503 now, Are you sure this repo is available?

**Comment by terrypacker** [comment]
Try it now.  We are configuring the system and it will potentially be down/up periodically for the next few weeks until we have a stable system.

**Comment by VergLsm** [comment]
Thanks, but there is nothing in the repo.

**Comment by terrypacker** [comment]
If you are trying to view the contents via a web browser use this link:

[https://maven.mangoautomation.net/#browse/browse/components:ias-release](https://maven.mangoautomation.net/#browse/browse/components:ias-release)

modbus4J 3.0.3 is in there

**Comment by VergLsm** [comment]
Thanks!
