### ISSUE TITLE
Modbus TCP request not prefix with 00 00 00 00 00 06 ?

### ISSUE THREAD

**Issue by zhangfx** [infiniteautomation/modbus4j#24]
Modbus TCP request not prefix with 00 00 00 00 00 06 ?

**Comment by terrypacker** [comment]
I am going to need a lot more information than this to help you out.  Please elaborate.

**Comment by minghu** [comment]
@zhangfx I know what you mean? tcp request have two mode,one is  encapsulated,it capsulation the rtu message.another is tcp native message. please see the document,check the  encapsulated　parameter

**Comment by terrypacker** [comment]
@minghu thanks, that's correct.  Modbus TCP uses a 6 byte header which is sent when using TCP when encapsulated=false, setting encapsulated=true will not use this header.
